language: minimal
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install build-essential texlive texlive-extra-utils --no-install-recommends
script:
    - make release ctan
